export type Region = {
  id: string;
  slug: string;
  name: string;
  lamin: number;
  lomin: number;
  lamax: number;
  lomax: number;
};

export type Flight = {
  icao24: string;
  callsign: string | null;
  origin_country: string | null;
  longitude: number | null;
  latitude: number | null;
  baro_altitude: number | null;
  velocity: number | null;
  true_track: number | null;
  vertical_rate: number | null;
  on_ground: boolean | null;
  squawk: string | null;
  region_id: string | null;
  time_position: string | null;
  last_contact: string | null;
  last_seen_at: string;
  source: "region" | "lookup";
};

export type TrackedFlight = {
  clerk_user_id: string;
  notification_email: string;
  flight_iata: string;
  flight_icao: string | null;
  airline_iata: string | null;
  airline_icao: string | null;
  flight_number: string | null;
  dep_iata: string | null;
  dep_icao: string | null;
  dep_name: string | null;
  dep_city: string | null;
  dep_lat: number | null;
  dep_lng: number | null;
  arr_iata: string | null;
  arr_icao: string | null;
  arr_name: string | null;
  arr_city: string | null;
  arr_lat: number | null;
  arr_lng: number | null;
  aircraft_icao: string | null;
  aircraft_model: string | null;
  status: string | null;
  hex: string | null;
  reg_number: string | null;
  lat: number | null;
  lng: number | null;
  alt: number | null;
  dir: number | null;
  speed: number | null;
  v_speed: number | null;
  dep_time_utc: string | null;
  dep_estimated_utc: string | null;
  arr_time_utc: string | null;
  arr_estimated_utc: string | null;
  dep_delayed: number | null;
  arr_delayed: number | null;
  dep_gate: string | null;
  dep_terminal: string | null;
  arr_gate: string | null;
  arr_terminal: string | null;
  arr_baggage: string | null;
  origin_lat: number | null;
  origin_lng: number | null;
  origin_label: string | null;
  last_location_at: string | null;
  drive_duration_minutes: number | null;
  drive_distance_meters: number | null;
  pickup_buffer_minutes: number;
  leave_by_utc: string | null;
  leave_stage: "idle" | "soon" | "now" | "sent";
  email_notifications: boolean;
  last_polled_at: string | null;
  last_signal_at: string | null;
  last_error: string | null;
  created_at: string;
  updated_at: string;
};

export type NotificationEvent = {
  id: string;
  clerk_user_id: string;
  event_key: string;
  event_type: string;
  subject: string;
  body: string;
  payload: Record<string, unknown>;
  sent_at: string;
  created_at: string;
};
